security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    in_memory: { memory: ~ }
    your_db_provider:
      entity:
        class: App\Entity\User
        property: apiKey

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: ~
      logout: ~
      stateless: true
      provider: your_db_provider
      guard:
        authenticators:
          - App\Security\TokenAuthentificator


  access_control:
    - { path: ^/api/admin, roles: ROLE_ADMIN }
    - { path: ^/api/subscriptions, roles: ROLE_ADMIN, methods: [POST, DELETE, PATCH] }
